// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package db

import (
	"database/sql/driver"
	"fmt"
	"time"
)

type Currency string

const (
	CurrencyUSD Currency = "USD"
	CurrencySGD Currency = "SGD"
)

func (e *Currency) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = Currency(s)
	case string:
		*e = Currency(s)
	default:
		return fmt.Errorf("unsupported scan type for Currency: %T", src)
	}
	return nil
}

type NullCurrency struct {
	Currency Currency
	Valid    bool // Valid is true if Currency is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullCurrency) Scan(value interface{}) error {
	if value == nil {
		ns.Currency, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.Currency.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullCurrency) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.Currency), nil
}

type Debt struct {
	ID            int64
	TransactionID int64
	SettledAmount string
}

type DebtDebtor struct {
	DebtID   int64
	DebtorID int64
	Amount   string
	Currency Currency
}

type Payment struct {
	ID        int64
	DebtID    int64
	DebtorID  int64
	Amount    string
	CreatedAt time.Time
	Currency  Currency
}

type Transaction struct {
	ID        int64
	Amount    string
	Currency  Currency
	Title     string
	CreatedAt time.Time
	PayerID   int64
}

type User struct {
	ID       int64
	Username string
	Email    string
}
