// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package db

import (
	"context"
)

type Querier interface {
	CreateAccount(ctx context.Context, arg CreateAccountParams) (Account, error)
	CreateDebt(ctx context.Context, transactionID int64) (Debt, error)
	CreateDebtDebtors(ctx context.Context, arg CreateDebtDebtorsParams) (DebtDebtor, error)
	CreatePayment(ctx context.Context, arg CreatePaymentParams) (Payment, error)
	CreateTransaction(ctx context.Context, arg CreateTransactionParams) (Transaction, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeleteDebt(ctx context.Context, id int64) error
	DeleteDebtDebtor(ctx context.Context, arg DeleteDebtDebtorParams) error
	DeletePayment(ctx context.Context, id int64) error
	DeleteTransaction(ctx context.Context, id int64) error
	DeleteUser(ctx context.Context, id int64) error
	GetAccount(ctx context.Context, username string) (Account, error)
	GetDebtById(ctx context.Context, id int64) (Debt, error)
	GetDebtByIdForUpdate(ctx context.Context, id int64) (Debt, error)
	GetDebtByTransactionId(ctx context.Context, transactionID int64) (Debt, error)
	GetDebtDebtorsByDebtAndDebtor(ctx context.Context, arg GetDebtDebtorsByDebtAndDebtorParams) (DebtDebtor, error)
	GetDebtDebtorsByDebtId(ctx context.Context, debtID int64) ([]DebtDebtor, error)
	GetDebtsOfDebtorId(ctx context.Context, debtorID int64) ([]DebtDebtor, error)
	GetPaymentsByDebtId(ctx context.Context, debtID int64) ([]Payment, error)
	GetPaymentsByDebtorId(ctx context.Context, debtorID int64) ([]Payment, error)
	GetPaymentsById(ctx context.Context, id int64) (Payment, error)
	GetTransactionById(ctx context.Context, id int64) (GetTransactionByIdRow, error)
	GetTransactionsByPayer(ctx context.Context, arg GetTransactionsByPayerParams) ([]GetTransactionsByPayerRow, error)
	GetUserById(ctx context.Context, id int64) (User, error)
	GetUserByUsername(ctx context.Context, username string) (User, error)
	ListUsers(ctx context.Context, arg ListUsersParams) ([]User, error)
	UpdateDebt(ctx context.Context, arg UpdateDebtParams) (Debt, error)
	UpdateDebtDebtor(ctx context.Context, arg UpdateDebtDebtorParams) (DebtDebtor, error)
	UpdatePayment(ctx context.Context, arg UpdatePaymentParams) (Payment, error)
	UpdateTransaction(ctx context.Context, arg UpdateTransactionParams) (Transaction, error)
	UpdateUser(ctx context.Context, arg UpdateUserParams) (Account, error)
}

var _ Querier = (*Queries)(nil)
