apiVersion: apps/v1
kind: Deployment
metadata:
  name: split-api-deployment
  labels:
    app: split-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: split-api
  template:
    metadata:
      labels:
        app: split-api
    spec:
      containers:
        - name: split-container
          image: ghcr.io/arkarsg/split:b81bca366d236aab99cc5fb31be6e001f8b04cc1
          ports:
            - containerPort: 8080
