apiVersion: apps/v1
kind: Deployment
metadata:
  name: split-api-deployment
  labels:
    app: split-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: split-api
  template:
    metadata:
      labels:
        app: split-api
    spec:
      containers:
        - name: split-container
          image: ghcr.io/arkarsg/split:3553f9699342f0857c4aeb29d69fbfd02c7de575
          ports:
            - containerPort: 8080
