name: Deploy to production

on:
  push:
    branches:
      - main 

jobs:
  deploy:
    name: Build image
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Login to ghcr.io
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GHCR_TOKEN }}

    - name: Build, tag, and push image to GHCR
      env:
        GHCR_USERNAME: ${{ github.actor }}
        GHCR_IMAGE: split
        IMAGE_TAG: ${{ github.sha }} 
      run: |
        docker build \
          -t ghcr.io/$GHCR_USERNAME/$GHCR_IMAGE:$IMAGE_TAG \
          -t ghcr.io/$GHCR_USERNAME/$GHCR_IMAGE:latest \
          .
        docker push ghcr.io/$GHCR_USERNAME/$GHCR_IMAGE --all-tags