name: Deploy to production

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Build image
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to ghcr.io
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_TOKEN }}

      - name: Build, tag, and push image to GHCR
        uses: docker/build-push-action@v6
        env:
          IMAGE_TAG: ${{ github.sha }}
        with:
          platform: linux/amd64,linux/arm64
          push: true
          tags: ${{ env.IMAGE_TAG }}
